# src/migrations/flyway/flyway.conf
flyway.url=jdbc:sqlite:data/crownstar.db
flyway.user=
flyway.password=
flyway.locations=filesystem:src/migrations/flyway/sql
flyway.baselineOnMigrate=true
flyway.outOfOrder=false
flyway.validateOnMigrate=true
flyway.cleanDisabled=true
